Bug fix bug representatives/10
cs169/fa23-chips-10.5-12 pull request #20
Opened 2023-11-28 23:48 UTC by PicklesTheFrog

found actual bug
returns all representatives
only creates new representatives, not duplicates, and adds them to database.

2023-11-29 01:58 UTC, Connor-Bernard requested changes

2023-11-29 01:58 UTC, Connor-Bernard commented on app/models/representative.rb
> +      Representative.create!({ name: name, ocdid: ocdid_temp,
Be careful with `create!` as it throws errors.  May wanna put together some error handling for this

2023-11-29 01:58 UTC, Connor-Bernard commented on app/models/representative.rb
> +      rep = build_or_create_rep(official, official.name, ocdid_temp, title_temp)
Since you're passing the official in, you shouldn't need to pass in the name (you should reference `official.name` from the `build_or_create_rep` method.

2023-11-29 01:59 UTC, PicklesTheFrog commented on app/models/representative.rb
> +      rep = build_or_create_rep(official, official.name, ocdid_temp, title_temp)
oh yeah...

2023-11-29 02:38 UTC, Connor-Bernard requested changes

2023-11-29 02:38 UTC, Connor-Bernard commented on app/models/representative.rb
> +        nil
Pretty sure this is the same thing as just using `create` instead of `create!`

2023-11-29 02:38 UTC, Connor-Bernard commented on app/models/representative.rb
> +      rep = build_or_create_rep(official, official.name, ocdid_temp, title_temp)
Resolved in [9181a11](https://github.com/cs169/fa23-chips-10.5-12/pull/20/commits/9181a1167f53636850ba5d559a3a8cf5e839b3ec)

2023-11-29 02:39 UTC, Connor-Bernard commented
Also make sure you're following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

2023-11-29 02:39 UTC, Connor-Bernard commented on app/models/representative.rb
> +        nil
If not, you should prob document with a comment why you're handling it that way.

2023-11-29 03:04 UTC, PicklesTheFrog commented on app/models/representative.rb
> +        nil
bruh ok

2023-11-29 03:49 UTC, Connor-Bernard requested changes

2023-11-29 03:49 UTC, Connor-Bernard commented on app/models/representative.rb
> +      Representative.create!({ name: official.name, ocdid: ocdid_temp,
```suggestion
      Representative.create({ name: official.name, ocdid: ocdid_temp,
```
It's still `create!` haha.

2023-11-29 03:55 UTC, Connor-Bernard commented on app/models/representative.rb
> +      Representative.create!({ name: official.name, ocdid: ocdid_temp,
Resolved by [baead5a](https://github.com/cs169/fa23-chips-10.5-12/pull/20/commits/baead5ab4cc9c2aef0947a008a83c6b920600fc3)

2023-11-29 03:55 UTC, Connor-Bernard commented on app/models/representative.rb
> +      Representative.create!({ name: name, ocdid: ocdid_temp,
Resolved by [baead5a](https://github.com/cs169/fa23-chips-10.5-12/pull/20/commits/baead5ab4cc9c2aef0947a008a83c6b920600fc3)

2023-11-29 03:57 UTC, Connor-Bernard requested changes

2023-11-29 03:57 UTC, Connor-Bernard commented on app/models/representative.rb
> +      Representative.new({ name: official.name, ocdid: ocdid_temp,
If its already in the db, it may be better to just fetch their record.  I realize that you don't have the PK here though, so if that's why you're doing it this way, you should prob leave a comment above that to explain since it's definitely not apparent.

2023-11-30 02:27 UTC, Connor-Bernard approved these changes
LGTM

2023-11-30 02:29 UTC, merged